name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=20.3.3
  - pandas=1.2.3
  - pytest=6.2.2
  - scipy>=1.7.0
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
